<?php if (count($flash) > 0) : ?>
    <div>
      <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
          <?= $message ?><br>
        <?php endforeach ?>
      <?php endforeach ?>
    </div>
<?php endif ?>
<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>
<hr>
<ul>
  <?php foreach ($filteredUsers as $filteredUser): ?>
    <?php if (!isset($filteredUser['status'])): ?>
      <li>
        <?= htmlspecialchars($filteredUser['nickname']) ?>
      </li>
    <?php endif ?>
  <?php endforeach ?>
</ul>