<?php if (count($flash) > 0) : ?>
    <div>
      <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
          <?= $message ?><br>
        <?php endforeach ?>
      <?php endforeach ?>
    </div>
<?php endif ?>
<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>
<hr>
<form action="/users/new" method="get">
  <input type="submit" value="New user" />
</form>
<hr>
<div>
  <p>Нажмите на пользователя для его просмотра</p> 
</div>
<ul>
  <?php foreach ($filteredUsers as $filteredUser): ?>
    <?php if (!isset($filteredUser['status'])): ?>
      <li>
        <a href="/users/<?= htmlspecialchars($filteredUser['id']) ?>"><?= htmlspecialchars($filteredUser['nickname']) ?></a>
      </li>
    <?php endif ?>
  <?php endforeach ?>
</ul>